### ISSUE TITLE
NPE Exceptions when Invoking JobStatusRequest

### ISSUE THREAD

**Issue by madjase** [NeverBounce/NeverBounceApi-Java#24]
Hey Guys,

I've been integrating into your service using the rather simple SingleCheck operation, which has been great if not slow. But due to the volume of emails we scan i've further integrated into the JobRequest operation to perform validations in bulk and faster.

We consume the latest version of your Java API, specifically version 4.0.5. When polling for JobStatuses we get parsing errors for response attribute "percent_complete", with the following stack trace. 

`Caused by: java.lang.IllegalArgumentException: key percent_complete
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:889)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:382)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:355)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:87)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81)
	at com.google.api.client.http.HttpResponse.parseAs(HttpResponse.java:459)
	at com.neverbounce.api.internal.HttpClientImpl.execute(HttpClientImpl.java:109)
	at com.neverbounce.api.internal.HttpClientImpl.getForObject(HttpClientImpl.java:84)
	at com.neverbounce.api.model.JobsStatusRequest.execute(JobsStatusRequest.java:23)
	at com.skymode.integrations.NeverbounceEmailSanitizer.sanitizeEmails(NeverbounceEmailSanitizer.java:137)
	at com.skymode.asynctasks.handlers.CustomerUploadAsyncTaskHandler.performEmailsSanitization(CustomerUploadAsyncTaskHandler.java:184)
	at com.skymode.asynctasks.handlers.CustomerUploadAsyncTaskHandler.handleTask(CustomerUploadAsyncTaskHandler.java:151)
	at com.skymode.asynctasks.handlers.CustomerUploadAsyncTaskHandler.handleTask(CustomerUploadAsyncTaskHandler.java:53)
	at com.skymode.asynctasks.handlers.AsyncTaskProcessor.call(AsyncTaskProcessor.java:58)
	at com.skymode.asynctasks.handlers.AsyncTaskProcessor.call(AsyncTaskProcessor.java:17)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:141)
	... 4 more
Caused by: java.lang.IllegalArgumentException: key percent_complete, field private int com.neverbounce.api.model.JobsStatusResponse.percentComplete
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:889)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:472)
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:781)
	... 27 more
Caused by: java.lang.NumberFormatException: For input string: "88.24"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.google.api.client.json.gson.GsonParser.getIntValue(GsonParser.java:90)
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:836)
	... 29 more`

It appears that the wrong datatype has been chosen in JobStatus to represent the percentage  complete, which comes back as a float.

**Comment by mmollick** [comment]
Thanks for the report Madjase, we'll be looking into this shortly!

**Comment by madjase** [comment]
https://github.com/NeverBounce/NeverBounceApi-Java/pull/25 PR fixes the issue reported here. Can we get it merged and a new release created?

**Comment by david-borrowman** [comment]
Hello madjase, 
This PR is slated for review today actually. We are hoping to have a new release ready by end of day. Thank you for your continued patience and for bringing this issue to our attention in the first place.

**Comment by madjase** [comment]
@david-borrowman thanks mate! I logged in to to open the PR myself, but realized someone had already done it which is always good news 💃

**Comment by david-borrowman** [comment]
Hello again,

I have tested and approved this request. It has been deployed as version 4.0.6. Thank you all for your contributions!
