### ISSUE TITLE
java.lang.IllegalArgumentException: expected primitive class

### ISSUE THREAD

**Issue by eInforma** [NeverBounce/NeverBounceApi-Java#40]
Hi,

We have integrated your email validation service and it works correctly, but sometimes exceptions are generated.
I think it may be due to a different response model than expected.

Exceptions:
```java
java.lang.IllegalArgumentException: expected primitive class, but got: class com.neverbounce.api.client.exception.NeverbounceApiException
	at com.google.api.client.util.Data.parsePrimitiveValue(Data.java:456) ~[google-http-client-1.29.0.jar:?]
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:871) ~[google-http-client-1.29.0.jar:?]
```

```java
java.lang.IllegalArgumentException: 
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:902) ~[google-http-client-1.29.0.jar:?]
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:362) ~[google-http-client-1.29.0.jar:?]
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:320) ~[google-http-client-1.29.0.jar:?]
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:298) ~[google-http-client-1.29.0.jar:?]
	at com.neverbounce.api.internal.HttpClientImpl.translateHttpResponseException(HttpClientImpl.java:178) ~[neverbounce-api-java-4.0.14.jar:?]
	at com.neverbounce.api.internal.HttpClientImpl.execute(HttpClientImpl.java:133) ~[neverbounce-api-java-4.0.14.jar:?]
	at com.neverbounce.api.internal.HttpClientImpl.getForObject(HttpClientImpl.java:95) ~[neverbounce-api-java-4.0.14.jar:?]
	at com.neverbounce.api.model.SingleCheckRequest.execute(SingleCheckRequest.java:48) ~[neverbounce-api-java-4.0.14.jar:?]
```

Please, would it be possible to add an exception that retrieves the response body?

Testing with CURL, sometimes we got responses with the Result `inconclusive`, not expected.

Thank you in advance

**Comment by mmollick** [comment]
Hey @eInforma, our API _shouldn't_ be returning `inconclusive` as a result code. In our logs we're not seeing any evidence of this sort of response, could you reach out to `support@neverbounce.com` with a list of emails you received this response from. It would also be helpful to know approximately what time frames you saw this response.
